# create a ckpt from sparc hf model

In [1]:
from sparc import load_model, download_huggingface
import torch
from paths import CKPT_DIR

/home/anli/Desktop/art-tts/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
multiling_ckpt = download_huggingface("model_multiling.ckpt")
multiling_ckpt = torch.load(multiling_ckpt)
multiling_ckpt["config"]["speech_model"] = './ckpt/wavlm-large'
#torch.save(multiling_ckpt, CKPT_DIR / "sparc_multi.ckpt")

In [3]:
ckpt = CKPT_DIR / "sparc_multi.ckpt"
coder = load_model(ckpt=ckpt,device="cpu")

/home/anli/Desktop/art-tts/.venv/lib/python3.12/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)


In [4]:
multiling_ckpt["state_dict"]["spk_ft"]
multiling_ckpt["config"]

{'crepe_model': 'full',
 'device': 'cuda',
 'fmax': 550,
 'fmin': 50,
 'freqcut': 10,
 'ft_sr': 50,
 'generator_ckpt': None,
 'generator_configs': {'bias': True,
  'channels': 512,
  'in_channels': 14,
  'kernel_size': 7,
  'nonlinear_activation': 'LeakyReLU',
  'nonlinear_activation_params': {'negative_slope': 0.1},
  'out_channels': 1,
  'resblock_dilations': [[1, 3, 5], [1, 3, 5], [1, 3, 5]],
  'resblock_kernel_sizes': [3, 7, 11],
  'spk_emb_size': 64,
  'upsample_kernel_sizes': [16, 10, 8, 4],
  'upsample_scales': [8, 5, 4, 2],
  'use_additional_convs': True,
  'use_weight_norm': True,
  'pitch_offset': 50,
  'pitch_rescale': 0.01,
  'pitch_axis': 12},
 'linear_model_path': None,
 'normalize': True,
 'pitch_q': 4,
 'speech_model': './ckpt/wavlm-large',
 'spk_emb_size': 64,
 'spk_ft_ckpt': None,
 'spk_ft_size': 1024,
 'sr': 16000,
 'target_layer': 9,
 'spk_target_layer': 0,
 'periodicity_threshold': 0.0,
 'reflect_loudness': False,
 'loudness_threshold': 0.05,
 'pitch_fit_scale': Fa

In [18]:
multiling_ckpt["state_dict"]["spk_ft"]

OrderedDict([('spk_fc.0.weight',
              tensor([[ 0.0158,  0.0175, -0.0076,  ..., -0.0657, -0.1091, -0.0442],
                      [ 0.0124, -0.0307, -0.0139,  ...,  0.0171,  0.0670,  0.0444],
                      [-0.0241,  0.0197, -0.0322,  ...,  0.0618,  0.0017, -0.0068],
                      ...,
                      [ 0.0389,  0.0023, -0.0217,  ...,  0.0159,  0.0179, -0.0166],
                      [ 0.0071,  0.0264, -0.0317,  ...,  0.0454,  0.0248, -0.0075],
                      [-0.0211,  0.0143, -0.0355,  ...,  0.0853, -0.0527, -0.0097]])),
             ('spk_fc.0.bias',
              tensor([-0.0228, -0.0217, -0.0083,  ...,  0.0120,  0.0201,  0.0192])),
             ('spk_fc.3.weight',
              tensor([[-0.0054, -0.0436,  0.0639,  ..., -0.0332,  0.0243,  0.0909],
                      [ 0.0007,  0.0725,  0.0857,  ..., -0.0007,  0.0435, -0.0198],
                      [ 0.0379,  0.0941, -0.0534,  ..., -0.0476, -0.0168, -0.0307],
                      ...,
     

In [11]:
multiling_ckpt["config"]["generator_configs"]

{'bias': True,
 'channels': 512,
 'in_channels': 14,
 'kernel_size': 7,
 'nonlinear_activation': 'LeakyReLU',
 'nonlinear_activation_params': {'negative_slope': 0.1},
 'out_channels': 1,
 'resblock_dilations': [[1, 3, 5], [1, 3, 5], [1, 3, 5]],
 'resblock_kernel_sizes': [3, 7, 11],
 'spk_emb_size': 64,
 'upsample_kernel_sizes': [16, 10, 8, 4],
 'upsample_scales': [8, 5, 4, 2],
 'use_additional_convs': True,
 'use_weight_norm': True,
 'pitch_offset': 50,
 'pitch_rescale': 0.01,
 'pitch_axis': 12}

In [12]:
ckpt = CKPT_DIR / "sparc_multi.ckpt"
bob = torch.load(ckpt)

In [17]:
multiling_ckpt["config"]["generator_configs"]

{'bias': True,
 'channels': 512,
 'in_channels': 14,
 'kernel_size': 7,
 'nonlinear_activation': 'LeakyReLU',
 'nonlinear_activation_params': {'negative_slope': 0.1},
 'out_channels': 1,
 'resblock_dilations': [[1, 3, 5], [1, 3, 5], [1, 3, 5]],
 'resblock_kernel_sizes': [3, 7, 11],
 'spk_emb_size': 64,
 'upsample_kernel_sizes': [16, 10, 8, 4],
 'upsample_scales': [8, 5, 4, 2],
 'use_additional_convs': True,
 'use_weight_norm': True,
 'pitch_offset': 50,
 'pitch_rescale': 0.01,
 'pitch_axis': 12}

In [ ]:
multiling_ckpt["state_dict"]["generator"]

OrderedDict([('input_conv.bias',
              tensor([-0.0557, -0.0601,  0.2086, -0.1854,  0.0356,  0.1978,  0.1566,  0.1361,
                       0.2057, -0.0898,  0.0638,  0.1569, -0.0763, -0.0209, -0.0427, -0.0371,
                      -0.1049,  0.1586, -0.1443, -0.0702, -0.1176,  0.0028, -0.1829,  0.0714,
                      -0.1600,  0.0312, -0.0033, -0.0041, -0.1146, -0.1133, -0.1241,  0.0052,
                       0.0272, -0.2075,  0.0328,  0.0132,  0.1820,  0.0598,  0.1261, -0.0337,
                      -0.0444,  0.1744,  0.1687, -0.1002,  0.1111,  0.1368,  0.0908,  0.0422,
                       0.0293,  0.1752, -0.0747,  0.0073,  0.1254, -0.0804,  0.0410,  0.0137,
                       0.1095, -0.0149, -0.1319,  0.0699, -0.1128, -0.0063,  0.0045, -0.1568,
                       0.0643,  0.0321,  0.1348, -0.0862, -0.0374,  0.1695, -0.1493,  0.0725,
                      -0.1357, -0.0472, -0.1371, -0.0522,  0.0345,  0.1372, -0.0319, -0.0819,
                       0.06

# Precompute articulatory features and spk_preemb for VoxCommunis

In [1]:
from paths import CKPT_DIR, DATA_DIR
from sparc import load_model
import argparse
from tqdm import tqdm
import logging
from pathlib import Path
import numpy as np
import torch
import os

ckpt = CKPT_DIR / "sparc_multi.ckpt"
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

coder = load_model(ckpt=ckpt, device=device)

/home/anli/Desktop/art-tts/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Using device: cpu


/home/anli/Desktop/art-tts/.venv/lib/python3.12/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)


In [2]:
from voxcommunis.io import read_manifest

manifest_path = DATA_DIR / "VoxCommunis" / "train-1h" / "manifests" / "fr.tsv"
manifest = read_manifest(manifest_path)

In [3]:
local_prefix = DATA_DIR / "VoxCommunis" / "audio"
jz_prefix = Path('/lustre/fsmisc/dataset/CommonVoice/cv-corpus-16.1-2023-12-06')

sample_id = 'common_voice_fr_27555348'
full_path, nframes = manifest[sample_id]
full_path = local_prefix / full_path.relative_to(jz_prefix)
full_path

PosixPath('/home/anli/Desktop/art-tts/src/../data/VoxCommunis/audio/fr/clips_wav/11/common_voice_fr_27555348.wav')

In [4]:
with torch.inference_mode():
    outputs = coder.encode(full_path, concat=True)

/home/anli/Desktop/art-tts/.venv/lib/python3.12/site-packages/torch/nn/functional.py:5962: UserWarning: Support for mismatched key_padding_mask and attn_mask is deprecated. Use same type for both instead.
  warnings.warn(


In [16]:
outputs["spk_emb"].shape

(64,)

In [8]:
truc = torch.load(CKPT_DIR / "sparc_multi.ckpt")

In [10]:
truc["config"]["spk_ft_ckpt"]

In [ ]:
coder.speaker_encoder.spk_enc = None
with torch.inference_mode():
    outputs = coder.encode([full_path], concat=True)

/home/anli/Desktop/art-tts/.venv/lib/python3.12/site-packages/torch/nn/functional.py:5962: UserWarning: Support for mismatched key_padding_mask and attn_mask is deprecated. Use same type for both instead.
  warnings.warn(


In [27]:
outputs["spk_emb"]

array([2.418554  , 0.6763854 , 1.59687   , ..., 0.29563534, 0.00889494,
       1.2266415 ], shape=(1024,), dtype=float32)

In [ ]:
outputs["features"]

(300, 15)

In [20]:
outputs.keys()

dict_keys(['features', 'spk_emb'])

# Working on generator

In [18]:
from model_ms.spk_encoder import SpeakerEncodingLayer
from paths import CKPT_DIR
import torch

ckpt = CKPT_DIR / "sparc_multi.ckpt"
sparc_ckpt = torch.load(ckpt)
spk_enc = SpeakerEncodingLayer(spk_ft_size=1024,spk_emb_size=64,)
spk_enc.load_state_dict(sparc_ckpt["state_dict"]["spk_ft"])
spk_enc.eval()
#spk_enc._modules["spk_fc"][0].weight
spk_ft = torch.randn(1, 1024)
with torch.no_grad():
    spk_emb = spk_enc(spk_ft)
spk_emb

tensor([[ 2.3770e+00,  2.3272e-01,  4.7047e+00,  4.2978e+00, -1.5580e+00,
         -4.7721e+00,  8.4002e-02,  4.0580e+00, -5.9887e+00, -5.1002e+00,
          3.8102e+00, -1.3143e+00,  9.1215e-03,  3.3045e+00,  1.0327e+01,
          4.4634e+00, -1.1600e+00,  7.4857e+00, -1.2677e+00,  3.7795e+00,
         -5.3142e+00,  1.3274e+00, -5.1168e+00,  1.4361e+00,  1.5011e+00,
          2.8638e+00, -1.3992e+00, -5.2162e+00, -2.0991e+00, -1.0324e+01,
          6.8884e+00, -4.9216e+00, -1.2840e+00,  4.7057e-03,  6.2058e+00,
         -4.5699e+00,  2.3461e+00,  6.4953e-01,  2.9699e+00, -8.3911e+00,
          1.0014e+01,  2.5357e+00, -1.5279e+00,  4.4407e+00, -2.5696e+00,
          2.8500e+00, -2.6187e+00, -4.2515e+00,  7.3470e-01,  1.0657e-01,
          5.3530e+00,  1.5485e+00, -4.7459e+00, -4.7737e-01, -6.9239e+00,
          2.2893e+00, -5.8279e+00, -1.5379e+00,  1.5395e+00, -1.2683e+00,
          6.7651e+00,  7.8719e-01, -1.1809e+00,  5.7607e+00]])

In [20]:
from model_ms.sparc_generator import HiFiGANGenerator, SpkHiFiGANGenerator

gen = HiFiGANGenerator(**sparc_ckpt["config"]["generator_configs"])

/home/anli/Desktop/art-tts/.venv/lib/python3.12/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)


In [ ]:
#spk_enc_out_dim = sparc_ckpt["state_dict"]["spk_ft"]['spk_fc.3.weight'].shape[0]
#assert sparc_ckpt["config"]["generator_configs"]["spk_emb_size"] == spk_enc_out_dim
spkgen = SpkHiFiGANGenerator(spk_ft_size=1024,**sparc_ckpt["config"]["generator_configs"])
spkgen.spk_enc.load_state_dict(sparc_ckpt["state_dict"]["spk_ft"])
spkgen.generator.load_state_dict(sparc_ckpt["state_dict"]["generator"])
spkgen.eval()
# generate tensor of shape (batch, channels, time)
c = torch.randn(1, 14, 100)  # (batch, channels, time)
spk_ft = torch.randn(1, 1024)  # (batch, spk_ft_size)
with torch.no_grad():    
    out = spkgen(c, spk_ft)

/home/anli/Desktop/art-tts/.venv/lib/python3.12/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)


In [ ]:
from data_ms import PhnmArticDataset, PhnmArticBatchCollate, PhnmDataset
from configs import params_v6
from torch.utils.data import DataLoader
from paths import DATA_DIR
from voxcommunis.sampler import LengthGroupedSampler, LengthGroupedLanguageUpSampler
from voxcommunis.decoder import FeatureDecoder
from voxcommunis.data import FeatureTokenizer

import torch

fd = FeatureDecoder(sum_diphthong=True)
tokenizer = FeatureTokenizer(fd)

split = "test-20h"
dataset_dir = DATA_DIR / "VoxCommunis"
split_dir = dataset_dir / split
separate_files = False
manifests_path = split_dir / "manifests" / "it.tsv"
alignments_path = split_dir / "alignments" / "it.align"

dataset = PhnmDataset(
        dataset_dir=dataset_dir,
        separate_files=separate_files,
        manifest_path= manifests_path,
        alignment_path= alignments_path,
        feature_tokenizer=tokenizer,
        reorder_feats=params_v6.reorder_feats,
        pitch_idx=params_v6.pitch_idx,
        loudness_idx=params_v6.loudness_idx,
        log_normalize_loudness=params_v6.log_normalize_loudness,
        random_seed=params_v6.random_seed,
    )

In [40]:
dataset.manifest[0]

('common_voice_it_19990048',
 (PosixPath('/lustre/fsmisc/dataset/CommonVoice/cv-corpus-16.1-2023-12-06/it/clips_wav/00/common_voice_it_19990048.wav'),
  69888))

In [54]:
from voxcommunis.io import read_manifest

man = read_manifest(manifests_path)

In [66]:
list((DATA_DIR / "VoxCommunis/encoded_audio_multi/fr/emasrc").glob("*.npy"))

[PosixPath('/home/anli/Desktop/art-tts/src/../data/VoxCommunis/encoded_audio_multi/fr/emasrc/common_voice_fr_18477147.npy'),
 PosixPath('/home/anli/Desktop/art-tts/src/../data/VoxCommunis/encoded_audio_multi/fr/emasrc/common_voice_fr_19963377.npy'),
 PosixPath('/home/anli/Desktop/art-tts/src/../data/VoxCommunis/encoded_audio_multi/fr/emasrc/common_voice_fr_22364800.npy'),
 PosixPath('/home/anli/Desktop/art-tts/src/../data/VoxCommunis/encoded_audio_multi/fr/emasrc/common_voice_fr_17334649.npy'),
 PosixPath('/home/anli/Desktop/art-tts/src/../data/VoxCommunis/encoded_audio_multi/fr/emasrc/common_voice_fr_19581598.npy'),
 PosixPath('/home/anli/Desktop/art-tts/src/../data/VoxCommunis/encoded_audio_multi/fr/emasrc/common_voice_fr_33757765.npy'),
 PosixPath('/home/anli/Desktop/art-tts/src/../data/VoxCommunis/encoded_audio_multi/fr/emasrc/common_voice_fr_19541131.npy'),
 PosixPath('/home/anli/Desktop/art-tts/src/../data/VoxCommunis/encoded_audio_multi/fr/emasrc/common_voice_fr_32638500.npy'),


In [ ]:
set(man.keys()).intersection

{'common_voice_it_20065755',
 'common_voice_it_18358683',
 'common_voice_it_22454823',
 'common_voice_it_19971534',
 'common_voice_it_19091664',
 'common_voice_it_32640087',
 'common_voice_it_19975664',
 'common_voice_it_19975542',
 'common_voice_it_20021323',
 'common_voice_it_30640523',
 'common_voice_it_20075762',
 'common_voice_it_19972075',
 'common_voice_it_21557159',
 'common_voice_it_20089018',
 'common_voice_it_19992043',
 'common_voice_it_19990074',
 'common_voice_it_32678010',
 'common_voice_it_19983234',
 'common_voice_it_20012180',
 'common_voice_it_19990013',
 'common_voice_it_20004475',
 'common_voice_it_18842215',
 'common_voice_it_17803165',
 'common_voice_it_20418277',
 'common_voice_it_20075127',
 'common_voice_it_20256186',
 'common_voice_it_20084138',
 'common_voice_it_20089929',
 'common_voice_it_25347745',
 'common_voice_it_19994542',
 'common_voice_it_19978128',
 'common_voice_it_17454188',
 'common_voice_it_34973557',
 'common_voice_it_19996991',
 'common_voice